README.md

This PR updates the main screenshot to use the most recent default wallpaper. Screenshot was taken using a virtual machine with a fresh install of the `aurora-dx` ISO.

chore: update screenshot to use new default wallpaper

---

.github/workflows/build-image-stable.yml

Bluefin just removed the kernel pin here: https://github.com/ublue-os/bluefin/pull/2021
I think Aurora should do the same.

fix: unpin 6.11.3 kernel

---

system_files/kinoite/usr/share/applications/documentation.desktop

The current URL https://docs.getaurora.dev/guides/intro/ leads to "Page Not Found".  This commit fixes that and instead points to https://docs.getaurora.dev/guides/basic-usage.

fix: aurora documentation URL

---

packages.json

All image builds are failing with the following error (from https://github.com/ublue-os/aurora/actions/runs/12336280554/job/34428627112):
```
error: Could not depsolve transaction; 2 problems detected:
Problem 1: conflicting requests
- installed package qt5-qtbase-gui-5.15.15-3.fc41.x86_64 obsoletes libadwaita-qt5 <= 1.4.2 provided by libadwaita-qt5-1.4.2-8.fc41.i686 from fedora
- installed package qt5-qtbase-gui-5.15.15-3.fc41.x86_64 obsoletes libadwaita-qt5 <= 1.4.2 provided by libadwaita-qt5-1.4.2-8.fc41.x86_64 from fedora
Problem 2: conflicting requests
- installed package qt6-qtbase-gui-6.8.1-5.fc41.x86_64 obsoletes libadwaita-qt6 <= 1.4.2 provided by libadwaita-qt6-1.4.2-8.fc41.i686 from fedora
- installed package qt6-qtbase-gui-6.8.1-5.fc41.x86_64 obsoletes libadwaita-qt6 <= 1.4.2 …
```

fix: remove libadwaita-qt{5,6} packages

---

system_files/shared/usr/share/ublue-os/aurora-cli/bling.sh

Port of https://github.com/ublue-os/bluefin/commit/76d7d71e900902845f3e715da85affe4dce52b7a from the bluefin repo. Should fix atuin getting sourced multiple times

fix: return on bling.sh if it already got sourced

---

.github/changelogs.py
Justfile
build_files/base/03-install-kernel-akmods.sh
system_files/shared/usr/bin/ublue-rollback-helper

GTS is only meaningful in Bluefin, so we can remove some of this dead code and outdated comments.

chore: remove references to GTS

---

build_files/base/03-install-kernel-akmods.sh

Pulling in Broadcom fix from Bluefin. See https://github.com/ublue-os/bluefin/pull/2070 and https://github.com/ublue-os/bluefin/issues/1783.
Related Discourse thread: https://universal-blue.discourse.group/t/more-broadcom-wifi-madness-possible-ujust-akmods-script-typo/4836/5

fix: remove wl akmod

---

build_files/base/18-workarounds.sh

This pin is no longer needed and was removed in https://github.com/ublue-os/bluefin/pull/1993. Pulling in the same changes.

fix: remove pkcs11-provider workaround

---

build_files/shared/build-dx.sh
system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kcm-about-distrorc

This PR contains two separate but related changes:
Mostly pulling from Bluefin's recent change https://github.com/ublue-os/bluefin/pull/2090 to make it so both `Aurora` and `Aurora-dx` count as a single entry in Homebrew's stats.
This should bump Aurora up a few spots on https://formulae.brew.sh/analytics/os-version/30d.
The `kcm-about-distrorc` file controls what is displayed in KDE's Info Center app. I noticed that Aurora's Info Center is using the `Variant` field in a way that is both redundant (i.e., it is just the `Name` field repeated) and different from how other KDE-based projects use that field, including Bazzite.
I feel that having the `Variant` field be empty for the Aurora image and "Developer Experience" for the Aurora-dx image is more in line with the spirit of the field. I …

chore(build-dx): consolidate os-release names

---

Justfile

The built images still have some labels referencing Bluefin. This PR updates some of the links to use the correct Aurora links. It also changes the image description label to match this repository's description.

chore: update some lingering bluefin references

---

system_files/shared/usr/bin/sb-key-notify

I discovered that the `sb-key-notify` service was repeatedly failing to run automatically on my install with the message "`Exec format error`". A quick search discovered that the issue is that this file is missing a shebang, so systemd/KDE don't know to launch it in a shell interpreter. I did a quick test on my installation with a modified script and it seems to work.
I see [some indication on the forums](https://universal-blue.discourse.group/t/various-errors-at-boot/5574) that some other people have seen this issue, although it's not clear if it's universally the case. I also took a quick look at bluefin, [which seems to have the same issue](https://github.com/ublue-os/bluefin/blob/main/system_files/shared/usr/bin/sb-key-notify) (in the script at least, not sure if GNOME is able to …

fix: add shebang to /usr/bin/sb-key-notify

---

build_files/dx/09-cleanup-dx.sh

There are no units named `pmie.service` or `pmlogger.service`. Trying to disable them is throwing errors that these units do not exist when building dx variants.
I pushed similar changes to Bluefin: https://github.com/ublue-os/bluefin/pull/2105
See: https://github.com/ublue-os/aurora/actions/runs/12604792860/job/35132349109
```
2025-01-03T22:43:58.4097786Z + systemctl disable pmie.service
2025-01-03T22:43:58.4218039Z Failed to disable unit: Unit pmie.service does not exist
2025-01-03T22:43:58.4218766Z Failed to disable unit: Unit pmie.service does not exist
2025-01-03T22:43:58.4219883Z The unit files have no installation config (WantedBy=, RequiredBy=, UpheldBy=,
2025-01-03T22:43:58.4220913Z Also=, or Alias= settings in the [Install] section, and DefaultInstance= for …
```

chore: remove systemd unit disable for unknown services on aurora-dx

---

artifacthub-repo.yml

This uses the correct artifacthub id to list aurora on artifacthub. tulip is going to PR the metadata changes. 
Feel free to add yourselves as owners at the bottom but leave mine in there as I'm running the org account in artifacthub.
For those not familiar with artifacthub it's a place that indexes cloud native artifacts, here's an example of what it looks like: https://artifacthub.io/packages/container/achillobator/achillobator

fix: artifacthub id

---

.github/workflows/generate-release.yml
.github/workflows/reusable-build-iso.yml
.github/workflows/reusable-build.yml
.github/workflows/shared/install-just.sh

Related to https://github.com/ublue-os/bluefin/pull/2106.
Lately, there are some flaky failures for jobs while installing `just`. For example, in the past few days, the following jobs to build images have failed:
- https://github.com/ublue-os/aurora/actions/runs/12607607121/job/35139162573
- https://github.com/ublue-os/aurora/actions/runs/12577208839/job/35054350351
The command `curl -L https://api.github.com/repos/casey/just/releases/latest | jq -r '.tag_name'` is sometimes returning "null" instead of an actual version, but it's difficult to tell if the curl call is failing or if it's returning a payload that is being parsed incorrectly.
In either case, adding `--retry` to curl and if it's still null, hardcoding a known good version should do the trick for now.

fix(actions): try to recover if just fails to install

---

system_files/shared/usr/libexec/ublue-system-setup

Two issues with the system setup script:
1. `$SYS_ID` is not defined anywhere, so we never actually take the branch to compare the product name.
2. I'm assuming `$SYS_ID` is supposed to be defined as the contents of `/sys/devices/virtual/dmi/id/product_name`, which is from Bazzite's [`/usr/libexec/hwsupport/sysid`](https://github.com/ublue-os/bazzite/blob/abeed9ace51ebb1297d975de4ceb72c41b4da363/system_files/desktop/shared/usr/libexec/hwsupport/sysid#L3). This string is something like `Laptop 13 (AMD Ryzen 7040Series)` which doesn't match the regex `Laptop (*`.
I discovered this when I noticed that I didn't have any of these tweaks on my Framework 13. I checked the first log entry for `ublue-system-setup.service` and it completed succesfully, but the script didn't take the correct branch …

fix: Framework 13 AMD support

---

system_files/shared/usr/lib/systemd/system/aurora-groups.service
system_files/shared/usr/libexec/aurora-groups.sh

forgot to make it executable so the service is failing

fix: make aurora-groups.sh executable 

---

.github/workflows/build-image-stable.yml

Related to https://github.com/ublue-os/aurora/issues/120. People with IPU6 cameras are reporting crash on boot with 6.11.11.
https://github.com/ublue-os/bluefin/pull/2146

fix: rollback stable images to 6.11.8 kernel

---

just/aurora-system.just

LXD was removed a while back but the ujust dx-group command still tries to add users to the lxd group and prints on error as no such group exists
This removes the lxd group from the ujust command

chore: remove lxd from dx-groups ujust

---

just/aurora-system.just

the `ujust benchmark`is broken as it tries to write somewhere thath is not writable.
copied this from https://github.com/ublue-os/bluefin/pull/2073

fix: fix ujust benchmark

---

system_files/shared/usr/libexec/ublue-flatpak-manager
system_files/shared/usr/libexec/ublue-user-setup

Verified it works in a VM. After reboot:
```
> flatpak override --show
[Context]
filesystems=xdg-config/gtk-4.0:ro;
[Environment]
QT_QPA_PLATFORMTHEME=kde
```
Closes #131 and #130.

feat: overrides for Qt/GTK theming in flatpaks

---

aurora_flatpaks/flatpaks

Fixes #132  
And removes adw-gtk flatpaks, we don't need those

feat: add org.gtk.Gtk3theme.Breeze for better GTK app integration

---

build_files/base/09-hwe-additions.sh

This will remove the unneeded Asus-firmware repo from the HWE builds. These are upstreamed so we will not need these anymore.

fix: fix hwe builds

---

build_files/base/17-cleanup.sh
just/aurora-apps.just
system_files/shared/usr/lib/systemd/system/usr-share-sddm-themes.mount
system_files/shared/usr/lib/tmpfiles.d/usr-share-sddm-themes.conf 

add sddm theme workaround from Bazzite.  [mount service](https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/kinoite/usr/lib/systemd/system/usr-share-sddm-themes.mountl) , [tmpfiles](https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/kinoite/usr/lib/tmpfiles.d/usr-share-sddm-themes.conf).
since i didn't see any issue regarding [sddm fallback to default theme ](https://github.com/ublue-os/bluefin/issues/1988) again on bazzite, i decided to re add this workaround again.

feat: add workaround for sddm theme (again)

---

.github/workflows/validate-just.yml
just/aurora-apps.just

I find myself relearning how to list the packages installed on the currently booted image so I figured that this could be handy to include by default.
I am also adding a GitHub action to validate justfiles.
```bash
❯❯ ujust list-installed-rpms
ostree commit: ebfe7b05027baa70709a82208b18684622f72b5e7a90fbdf7130770ca5f720a6
ImageMagick-1:7.1.1.41-1.fc41.x86_64
ImageMagick-libs-1:7.1.1.41-1.fc41.x86_64
Judy-1.0.5-37.fc41.x86_64
LibRaw-0.21.3-1.fc41.x86_64
ModemManager-1.22.0-4.fc41.x86_64
ModemManager-glib-1.22.0-4.fc41.x86_64
NetworkManager-1:1.50.0-1.fc41.x86_64
NetworkManager-bluetooth-1:1.50.0-1.fc41.x86_64
NetworkManager-config-connectivity-fedora-1:1.50.0-1.fc41.noarch
NetworkManager-libnm-1:1.50.0-1.fc41.x86_64
NetworkManager-openconnect-1.2.10-6.fc41.x86_64 …
```

feat(ci): add ujust recipe to list installed rpms

---

Justfile

A recent refactor of the Justfile accidentally dropped these two lines, which is causing the NVIDIA `stable-daily` images to have mismatched driver / graphics toolkit versions.
This should resolve #148.

fix(nvidia): use correct kernel flavor for akmods with stable-daily

---

build_files/base/05-override-install.sh

Some context from Discord:
> @ledif
> - If we use negativo's libheif (current situation), we get better support for HEIF images (what is missing due to patents?) but old Intel hardware crashes
> - If we use Fedora's libheif, we lose some HEIF support (again, not sure what) but older Intel is supported
> ... Maybe we can just override the override directly in Aurora instead of starting a debate in the packages repo about what should be included by default for Bazzite as well
> @castrojo 
> yeah, do it in aurora
> I can almost guarantee bazzite won't turn off heif for people on i915
Related to https://github.com/ublue-os/aurora/issues/8.

fix: use libheif from Fedora to support older Intel platforms

---

.github/workflows/reusable-build-iso.yml

This PR removes the workflow step of renaming the HWE ISOs to Asus and Surface ones. They are the same now and do not need to be duplicated. 
Website PR: https://github.com/NiHaiden/aurora-web/pull/25
Closes: #134

feat: Do not duplicate isos anymore and upload -hwe ones instead

---

build_files/base/01-build-fix.sh

Bluefin has a few more overrides here than us and the glibc overrides likely would have fixed last night's build skew failures.

chore(build): port improvements from Bluefin's skew fixes

---

just/aurora-system.just
system_files/shared/usr/libexec/ublue-flatpak-manager

This updates install-system-flatpaks just recipe to allow passing a list of flatpaks, this will be compared with the list of flatpaks in the repo and install new flatpaks when they differ. This is called on boot through ublue-flatpak-manager, which allows keeping flatpaks in sync for current users.
Fixes https://github.com/ublue-os/aurora/issues/147

feat: install new flatpaks for current users on boot

---

build_files/base/18-workarounds.sh
just/aurora-system.just

The previous comparison approach didn't work as newlines in the list were trimmed to form one string with all the flatpaks, and comm compares line by line.
This uses bash arrays to properly manipulate the lists, additionally it sends a notification when new flatpaks are installed.

fix: flatpak comparison in ujust script

---

system_files/shared/usr/libexec/ublue-flatpak-manager
system_files/shared/usr/libexec/ublue-user-setup

This works with the breeze cursor, ymmv with other cursor themes
Before:
After:

fix: make cursor smaller in gtk flatpaks when fractional scaling is enabled

---

build_files/base/02-install-copr-repos.sh
build_files/base/05-override-install.sh
build_files/base/17-cleanup.sh

Install the scx-scheds package from the CachyOS addons copr instead of ublue staging.
CachyOS repo has up to date package for scx-scheds.

feat: change to CachyOS addons repo for scx-scheds package

---

just/aurora-system.just

This very small added flag ensures we don't collide with fedora flatpaks that might be installed by a user and just reinstalls them from scratch from flathub.
Credits go to @Zeglius <3.

fix: Justfile to avoid collision with fedora flatpaks

---

system_files/shared/usr/share/ublue-os/just/10-update.just

From https://github.com/ublue-os/bluefin/pull/2189
Pulls in aurora specific changelogs and formats them nicely.
changelogs-fedora will pull fedora package changelogs

feat(just): add aurora-specific changelogs

---

just/aurora-system.just
system_files/dx/usr/lib/dracut/dracut.conf.d/80-vfio.conf
system_files/dx/usr/libexec/aurora-dx-kvmfr-setup

this makes vfio bootc compliant as initramfs regeneration will no longer be required as the modules will be pre-included into initramfs.

feat: add vfio modules to image

---

system_files/dx/etc/skel/.config/Code/User/settings.json

Automated updates aren't useful since updates are handled through the image.  It just creates a pop-up that nobody can do anything with

chore: disable vscode automated updates

---

just/aurora-apps.just

fix: add 23.08 runtimes for mangohud and gamescope for lutris/heroic

---

system_files/dx/usr/lib/systemd/user/aurora-dx-user-vscode.service
system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service
system_files/shared/usr/lib/systemd/user/ublue-user-setup.service

We enable our `systemd --user` services for every user. The SDDM greeter run as the `sddm` user, so our `ublue-*` services are started when the login screen is displayed. Furthermore, the `sddm` users has an actual home directory.
```bash
❯ getent passwd sddm
sddm:x:981:977:SDDM Greeter Account:/var/lib/sddm:/usr/sbin/nologin
```
When we look at this directory, we see it has some state related to our ublue services.
```bash
❯ sudo ls -l /var/lib/sddm/.local/share/ublue
total 12
-rw-r--r--. 1 sddm sddm 2 Jan 23 09:58 flatpak_manager_version
-rw-r--r--. 1 sddm sddm 0 Nov 26 09:22 framework-initialized
-rw-r--r--. 1 sddm sddm 2 Feb  8 08:48 user-setup
-rw-r--r--. 1 sddm sddm 2 Nov 26 09:22 vscode-configured
```
```
Feb 08 08:48:46 systemd[1]: Started user@981.service - User Manager for UID …
```

fix: only run ublue user services for human users

---

packages.json

Brings back the kde-welcome screen.
There was talk that this would be nice to have regarding when new plasma versions come out.

feat: bring back kde-welcome

---

system_files/dx/etc/skel/.config/Code/User/settings.json

https://github.com/ublue-os/bluefin/pull/2198
Add nerd font symbols as a fallback font for vscode so users don't have to change to a nerd font if using default fonts.

feat: add nerd fonts fallback to vscode config

---

system_files/shared/usr/libexec/ublue-user-setup

Setting `QT_QPA_PLATFORMTHEME=kde` for Flatpaks that don't allow filesystem access apparently breaks XDG Desktop Portal support.
Verified in a VM that this variable is unset when running Flatpaks. The file picker is now correctly using the XDG Portal picker instead of the sandboxed KDE picker.
```
❯ flatpak override --user --show
[Context]
filesystems=xdg-config/gtk-4.0:ro;
unset-environment=QT_QPA_PLATFORMTHEME;
[Environment]
QT_QPA_PLATFORMTHEME=
USE_POINTER_VIEWPORT=1
```
Closes https://github.com/ublue-os/aurora/issues/224.

fix: remove flatpak override for QT_QPA_PLATFORM

---

system_files/kinoite/etc/skel/.config/starship.toml

feat: add starship config

---

build_files/base/18-workarounds.sh
build_files/shared/build-base.sh
build_files/shared/build-dx.sh

Ported from https://github.com/ublue-os/bluefin/pull/2215/
main has removed the workaround since upstream should have fixed it.
Relates: https://github.com/ublue-os/main/pull/721

chore: remove alternatives workaround

---

just/aurora-apps.just

The gaming flatpak installation ujust recipe had comment lines that are unneccasary and break the command chain

fix: remove un-needed comments from gaming flatpak install recipe

---

.github/changelogs.py
just/aurora-system.just
system_files/kinoite/usr/bin/boot-to-windows
system_files/kinoite/usr/share/applications/boot-to-windows.desktop

add boot-windows script from [bazzite](https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/bin/boot-windows), need better logo tbh, and small changes to changelogs generator.
inspired by this [blogpost](https://web.archive.org/web/20220522051320/https://www.ahoneycutt.me/blog/systemd-boot/).

feat: add desktop entry for boot into windows easily

---

packages.json

This fixes mutliple reports of the iso size increasing by a lot because nerd fonts pull in about 1 gigabyte worth of data from the terra repo.

fix: update package list to only include symbol nerd fonts

---

Justfile

This was used today to rollback the `latest` tag, which was broken this time instead of `stable-daily`. These changes give us the ability to quickly roll these things back.

feat: expand recipe to rollback broken NVIDIA images

---

.github/workflows/build-image-latest-hwe.yml
.github/workflows/build-image-latest-main.yml

Unpins the latest and hwe streams kernel
Once kernel-cache has the new 6.13.5 kernel this can be merged

chore: unpin kernel on latest and hwe streams

---

system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md

Removes some broken flatpak links from the motd script. Also renames some Bluefin mentions to Aurora
Closes https://github.com/ublue-os/aurora/issues/257

fix: update motd tips script

---

build_files/shared/build-base.sh

Fixes build, should be reverted whenever https://github.com/rpm-software-management/dnf5/issues/2134 is fixed upstream

fix: downgrade dnf5 to 5.2.10 to workaround pulling signing keys

---

build_files/base/07-base-image-changes.sh

This adds a one-line change to the build files that will alter the Discover Desktop Shortcut with a command-line argument so that it only shows Flatpaks instead of Flatpaks, Themes and other stuff.

feat: tell discover to only show flatpaks

---

build_files/base/05-override-install.sh

This renames the patched kf6-kio to match Terra's naming, it also simplifies version matching.
Fixes build.

fix: rename kf6-kio package

---

.github/CODEOWNERS

Our CODEOWNERS file was not properly set, so it only added the last approver (me) to new pull requests
Github docs https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> If you want to match two or more code owners with the same pattern, all the code owners must be on the same line. If the code owners are not on the same line, the pattern matches only the last mentioned code owner.

fix: update CODEOWNERS

---

build_files/base/03-install-kernel-akmods.sh

Some cleanup before F42 beta starts
This isn't shipped by fedora (atleast anymore) so we shouldn't diverge too much. 
Bluefin also doesn't carry this.
If someone for some reason needs this, they can propably do https://github.com/p1u3o/tidbits?tab=readme-ov-file#broadcom

chore: remove wl akmod

---

build_files/base/02-install-copr-repos.sh
build_files/base/05-override-install.sh
build_files/base/17-cleanup.sh
packages.json

Cleanup before F42 betas
This doesn't have f42 packages atleast at this moment and propably not really used anyway
Already talked with tulip if this could be brought to ublue-os copr

chore: remove fw-fanctrl

---

just/aurora-system.just

I don't think this should be hidden nowadays anymore

chore: remove hidden system-flatpak-install from the ujust list

---

build_files/base/03-install-kernel-akmods.sh

Fedora 42 is now [available](https://download.opensuse.org/repositories/hardware:/razer/Fedora_42/) for openrazer-daemon

chore: enable openrazer kernel module for Fedora 42

---

build_files/base/03-install-kernel-akmods.sh

rpmfusion can break during fedora beta. Gate the beta so that it builds even if rpmfusion is broken.
No need for stupid hacks and whatnot

chore: beta should build even if rpmfusion isn't working

---

build_files/base/03-install-kernel-akmods.sh

PipeWire should now provide the features which previously made v4l2loopback necessary. This removes the v4l2loopback install.
Additionally, this removes rpmfusion and installs v4l2loopback from terra
Picked from https://github.com/ublue-os/bluefin/pull/2330

feat: remove rpmfusion and replace v4l2loopback from terra

---

packages.json

Remove topgrade from this cycle. It is available from brew.

chore: remove topgrade

---

packages.json

This font was removed in #319 but it is the default terminal font, so we should keep it on the image.

fix: add default terminal font back to image

---

dx_flatpaks/flatpaks

DevPod isn't yet published in flathub but its pretty much waiting for approval review
EDIT: It should be available in "4-5 hours"

feat(dx): add devtoolbox and DevPod flatpaks to -dx

---

build_files/base/05-override-install.sh

Terra is removing the -switcheroo tag from kf6-kio
Propably needs to be force merged thanks to HWE :)

fix: rename kf6-kio package on terra

---

packages.json

Adds back the fw-fanctrl package from ublue copr for fedora 42 only

feat: bring back fw-fanctrl for f42

---

build_files/base/02-install-copr-repos.sh
build_files/base/17-cleanup.sh
just/aurora-apps.just
packages.json

Adds the sunshine copr, installs sunshine package and disables the global service.
also adds a ujust script to enable the user service for sunshine

feat: enable sunshine + add ujust script

---

build_files/base/03-install-kernel-akmods.sh

Also partial revert "feat: install v4l2loopback from terra (#2339)"
This reverts commit 3ff7e659d827648c0a7435f5ed7f711226e17929.
Also this removes the terra installed v4l2loopback in a partial revert of commit fa23c87eaef6677dfb44ac816a0c390923e908dc.

fix: Revert "feat: remove v4l2loopback and rpmfusion for Fedora 42+"

---

build_files/dx/04-override-install-dx.sh
packages.json
system_files/dx/etc/yum.repos.d/docker-ce.repo

Replaces the "testing" packages with dockers stable repo packages

chore: use docker packages from the stable repo

---

build_files/base/09-hwe-additions.sh

surface is still missing some packages, switch to skipping them until they are available but enable builds
https://github.com/ublue-os/bluefin/pull/2378

fix(hwe): switch to skip-unavailable

---

packages.json

This is now as a flatpak, i thought we had removed this already

chore: remove skanpage rpm

---

build_files/base/00-image-info.sh

from https://github.com/ublue-os/bluefin/pull/2355

fix(nvidia-open): correctly identify nvidia-open on image-info.json

---

just/aurora-apps.just

It is unnecessary and inconsistent with the other install commands which have no alias.

fix: remove incus alias

---

system_files/shared/usr/libexec/ublue-user-setup

devpod flatpak has issue with nvidia, this sets env override for the flatpak devpod app

fix: devpod flatpak fix for nvidia

---

just/aurora-system.just

from https://github.com/ublue-os/bluefin/pull/2413

fix: show prompt for installing stress-ng via brew if not installed

---

build_files/base/07-base-image-changes.sh

Sets up SELinux and firewalld so that creating a Samba usershare through Dolphin (right click a folder -> Properties -> Share) works without silently failing, as well as preventing Samba from automatically exporting users' home folder as a share.

fix: make samba usershares work OOTB

---

system_files/shared/usr/bin/ublue-rollback-helper

Adds small guards to rebase-helper ujust.
Until stable gets Fedora 42, if the user is on `latest` already, not show other streams.
IF on `stable or stable-daily` then allow all but add a note that latest wont allow rollback until stable is f42

fix(rebase-helper): Guard rebase helper

---

aurora_flatpaks/flatpaks
packages.json

Kcharselect has a flatpak
https://flathub.org/apps/org.kde.kcharselect
We don't need it in the image, it's just a tool to copy characters from all installed fonts.

chore: remove kcharselect

---

build_files/base/03-install-kernel-akmods.sh
system_files/shared/usr/lib/bootc/install/20-aurora.toml

This just adds a default filesystem type for aurora (btrfs) (makes it so bootc install to-disk works w/o modifications), and adds nvidia kargs on nvidia builds, shouldnt affect anything retroarctively
just so we are up-to-date once we are implementing readymade

chore: add upstream bootc config for nvidia and bootc install

---

system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service

Previous solution could overwrite users hostname. This creates an empty file if it  doesn't exist

fix: /etc/hostname fixup

---

README.md

Also remove the note about the README being under construction.  The split has been over for a while.

chore(readme): Replace CONTRIBUTING link from Bluefin to Universal Blue

---

.github/workflows/build-image-stable.yml

This is required because Fedora CoreOS stable moved to a rawhide kernel which isn't available in F41.

chore: pin Stable to kernel 6.13.8

---

packages.json

chore: remove fedora-chromium-config* and fedora-bookmarks package

---

build_files/base/17-cleanup.sh

Enables uupd without the condition check
should close https://github.com/ublue-os/aurora/issues/426

fix(uupd): enable the service without conditions

---

build_files/base/07-base-image-changes.sh

Restores the firmware updater (fwupd) backend to Discover.

fix: restore fwupd backend to discover

---

system_files/shared/usr/bin/ublue-rollback-helper

now that we have F42 available on stable, no need for guards

chore: remove guards from rollback-helper

---

Justfile

Move back to F41 installer because of the wayland issues users are seeing with the installer

fix(iso): Use F41 for ISO

---

system_files/shared/usr/libexec/ublue-user-setup

This should be fixed with Fedora 42 and not needed

chore: remove override for cursor in gtk  apps

---

build_files/base/18-workarounds.sh

It apparently breaks qualcomm WiFi chips
Ported from bluefin
https://github.com/ublue-os/bluefin/pull/2574
See: https://bugzilla.redhat.com/show_bug.cgi?id=2365882
> Downgrading to `atheros-firmware-20250311-1.fc42` fixed the issue

fix(pin): atheros-firmware downgrade to 20250311-1

---

system_files/dx/usr/libexec/aurora-dx-groups
system_files/shared/usr/libexec/aurora-groups.sh

the script was missing creation of the /etc/ublue dir, just like was
done on the devmode script a while back
closes https://github.com/ublue-os/aurora/issues/521

fix: aurora-groups service

---

.github/workflows/reusable-build-iso-anaconda.yml
iso_files/configure_iso_anaconda.sh

Creates a LiveCD environment but uses the old Anaconda installer without the webui (which doesn't work for KDE atm)

feat(iso): Move to LiveCD with old anaconda installer

---

build_files/base/07-base-image-changes.sh

Right now the default sddm background is the fedora wallpaper.
Fedora changed the backgrounds from png to jxl (now that they ship jxl wallpapers with F42) they also set `default.jxl` in `/usr/share/sddm/themes/01-breeze-fedora/theme.conf` so this sets the SDDM wallpaper to whatever is the regular wallpaper.

fix: set SDDM wallpaper to the regular default wallpaper

---

just/aurora-system.just

Reports from Discord that the main ujust is broken with https://github.com/ublue-os/aurora/pull/531. The simple fix is to remove the unintended indention.
```
ujust --choose
error: Unknown start of token '-'
——▶ just/60-custom.just:270:22
│
270 │   flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
│                      ^
```

fix(ujust): unindent recipe name after refactor

---

build_files/base/17-cleanup.sh

We have moved to uupd, so this can be disabled so it doesn't unneccessarily run the rpm-ostreed timer

chore: disable old rpm-ostreed-automatic.timer

---

system_files/shared/etc/skel/.config/starship.toml

Adds a little notification to starship prompt when there is new image deployment waiting for reboot

feat: add new deployment notification to starship prompt

---

system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh

This PR updates the Framework 13 (AMD) setup logic to stop applying the atkbd suspend udev workaround if the system is running BIOS version 3.09 or newer. Framework resolved the underlying issue last month in [BIOS 3.09](https://knowledgebase.frame.work/framework-laptop-13-bios-and-driver-releases-amd-ryzen-7040-series-r1rXGVL16) ("Fixed IRQ1 wake issues on Linux"), so the rule is no longer needed.
I manually invoked the script on my laptop and it successfully detected that I am running 3.09 and it removed the workaround.

fix: remove Framework 13 (AMD) udev workarounds with latest BIOS

---

build_files/base/03-install-kernel-akmods.sh

For some reason (propably legacy debt) this was trying to pull it from two different places, which broke our builds.

fix: v4l2loopback

---

iso_files/system-flatpaks.list

Pika doesn't work with password protected archives OOTB on KDE

feat: change Pika Backup to Vorta

---

iso_files/system-flatpaks.list

Removes Boxbuddy and replaces it with Distroshelf.
Maybe in the future we can replace this with Kontainer once it matures

feat: change Boxbuddy to Distroshelf

---

aurora_flatpaks/flatpaks

we forgot to change it here as well
https://github.com/ublue-os/aurora/pull/570
https://github.com/ublue-os/aurora/pull/552

fix: actually replace boxbuddy with distroshelf

---

build_files/base/05-override-install.sh

Someone on discord with previously affected hardware showed a working bazzite kde the other day which never shipped this workaround.
We don't need this anymore, this must have gotten resolved upstream with 1.19.8 https://github.com/strukturag/libheif/releases/tag/v1.19.8
I tried an image with this change on my laptop that was previously affected and this totally works now!
https://github.com/ublue-os/aurora/issues/8

chore: remove libheif workaround

---

build_files/base/07-base-image-changes.sh

we do not ship gnome-system-monitor

chore: remove hidden desktop entry section for gnome-system-monitor

---

build_files/base/05-override-install.sh
packages.json

when a new KDE version hits the repos and it's not in the base image yet then the plasma-firewall version will be newer than what's on the image.
removes the indent and doesn't call awk anymore for explicitly installing kf6-kio from terra

fix: prevent plasma-firewall package skew

---

build_files/base/18-workarounds.sh

6.9.1-3 reverted the fedora patch that caused the initial breakage
https://bugzilla.redhat.com/show_bug.cgi?id=2375356
https://bugs.kde.org/show_bug.cgi?id=506316
https://github.com/ublue-os/aurora/commit/92b62319a809f4247bcad6cac047109d99214cc5

chore: revert qt6-qtwayland pin

---

.github/workflows/reusable-build.yml
Justfile

this makes rechunk use rootfull container storage on Github runners, enabling the use of the [btrfs container storage action](https://github.com/ublue-os/container-storage-action) that utilizes the free space of `/mnt` inside the gh runner
It should not fail anymore because we were mixing rootfull and rootless container storages

feat(ci): consistently use rootful container storage

---

.github/workflows/reusable-build.yml

This prefixes everything with sudo so the rooful container storage is used, the action previously loaded the rootfull image into the user container storage sometimes leading to running out of space on the biggest nvidia-dx image
https://github.com/ublue-os/aurora/actions/runs/16603485215/job/46969177272

fix(ci): load rechunked image into rootfull storage

---

just/aurora-system.just

stole this from bazzite https://github.com/ublue-os/bazzite/commit/1b102aef9424d8916d5ba8a714e20438ae9e9b06

chore: copy toggle iwd ujust recipe from bazzite

---

just/aurora-apps.just
packages.json

fedoras package of ramalama is old and updates slowly. Moving this to brew
Also adds ujust recipe to install ai tools
Required: https://github.com/ublue-os/packages/pull/827

chore: remove ramalama from image

---

build_files/base/18-workarounds.sh

There is some weird interaction with the latest NVIDIA drivers and apps using the Gtk4 toolkit. Pulling in https://github.com/ublue-os/bazzite/commit/bb0e8f0d9cfe26efa56eed0fa75b7d1e8c110c46 which might fix it.

fix(nvidia): Force NGL for GTK apps for now

---

build_files/base/11-bazaar.sh

bazzite removed it with
https://github.com/ublue-os/bazzite/commit/8785c414f066b4b726de9f5199fbf79de75ed016
tested on my VM that was previously busted

chore: remove bazaar libdex workaround

---

system_files/shared/usr/share/kde-settings/kde-profile/default/xdg/kdeglobals

we do not ship kcm-plymouth, we don't need to disable it

chore: remove unnecessary plymouth kcm disablement

---

system_files/shared/usr/lib/sddm/sddm.conf.d/kde_settings.conf

This sets the new sddm theme from:
https://github.com/ublue-os/packages/pull/816
This file actually sets the theme as the default, this won't change any existing setups as /etc wins over /usr. It just changes fedora to aurora anyway at the moment. No visual changes.
It can't be in packages repo as it conflicts with kde-settings-sddm package and I don't feel like ripping the fedora package apart right now.

feat: add sddm setting

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

- Damask doesn't work in KDE.
- Cameractrls requested in https://github.com/ublue-os/aurora/issues/854#issuecomment-3205021402

feat(bazaar): remove Damask, add Cameractrls

---

build_files/base/11-bazaar.sh

We have the sledgehammer fix  in workarounds.sh file for all gtk4 apps [here](https://github.com/ublue-os/aurora/blob/7158f2108bbcb03224a5632ae17e7c7f61a1aae8/build_files/base/18-workarounds.sh#L25)

chore: remove the bazaar specific nvidia fix

---

.github/changelogs.py

When running `ujust changelog` in a maximized terminal it renders like this:
There's the automatic rendering line break after "more", but then also the manual line break after "information".
This PR removes the manual line break, so that the rendering can take care of line breaks.

style: remove manual linebreak

---

system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt

Adds KDE applications that we have as native rpm packages to Bazaars blocklist
Ark
Filelight
KFind
Konsole
KWalletManager
Kate
fixes https://github.com/ublue-os/aurora/issues/891

chore(bazaar): block kde apps that are native

---

system_files/shared/usr/share/ublue-os/bazaar/config.yaml

fixes: https://github.com/ublue-os/aurora/issues/939

fix(bazaar): always use white text color

---

.github/changelogs.py

added some fixes for the authors section, specifially with names (spaces etc)
https://github.com/ublue-os/bazzite/pull/3221
still would  prefer to use github usernames and link the username to their profile but haven't figured out a way to make it work correctly

fix: changelogs better formatting for authors

---

packages.json

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f2c61db29f277b9c80de92102fc532cc247495cd
I don't know why we have this in the first place. No one should be surprised by the way this has been going, I don't care if we remove it with 6.17 or now.
https://github.com/ublue-os/bluefin/pull/1008

chore: remove bcache-tools

---

build_files/base/07-base-image-changes.sh
build_files/base/11-bazaar.sh

Removes the offline docs icon from the KDE panel
@renner0e  mentioned that it doesn't also show on the Kickoff menus favorites part either, which is kind of  strange as its set up same as like Bazaars icon is..

fix: offline docs away from panel

---

system_files/shared/usr/bin/kde-ptyxis

Refactor argument handling to replace standalone '-e' with '--'.
Closes https://github.com/ublue-os/aurora/issues/1061
from https://github.com/ublue-os/bazzite/pull/3174/files

fix: Improve argument parsing in kde-ptyxis script
