ublue-os/aurora

- .github/workflows/build-images.yml
> chore(ci): don't build GTS here

- README.md
> docs: update repobeats

- README.md
A small "under construction" disclaimer at the top.
> chore(readme): Add note about README is a WIP

- build_files/base/07-base-image-changes.sh
This PR restores the konsole terminal in it's original form and makes it available again.
> feat: restore konsole terminal

- build_files/base/03-install-kernel-akmods.sh
> fix: revert "fix: remove wl akmod"

- build_files/base/00-image-info.sh
> chore: remove VERSION_CODENAME from os-release

- README.md
> chore: fix link to badge for the stable build

- just/aurora-apps.just
Closes #76. Thanks to @nisel11 for the snippet.
> feat: add ujust recipe to install gaming flatpaks

- build_files/base/09-hwe-additions.sh
Pulling in changes from https://github.com/ublue-os/bluefin/pull/2123.
> fix(hwe): match Bluefin's HWE for Surface devices

- just/aurora-system.just
Port of my PR in Bluefin https://github.com/ublue-os/bluefin/pull/2140.
> fix(just): fix configure-vfio recipe

- .github/workflows/build-image-stable.yml
> fix: pin kernel to 6.11.11 for stable images

- just/aurora-apps.just
add just for installing openrazer gui apps and opentabletdriver service distrobox from [Bazzite](https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just#L130)
> feat: add just for installing openrazer gui apps and opentabletdriver service distrobox

- just/aurora-apps.just
change opentabletdriver just recipe from distrobox to flatpak from flathub
> feat: change opendrivertablet to flatpak version from flathub

- system_files/shared/usr/lib/systemd/system/ublue-system-setup.service
- system_files/shared/usr/libexec/ublue-system-setup
> fix: Update ublue-system-setup

- Containerfile
- Justfile
- build_files/base/00-image-info.sh
Just like https://github.com/ublue-os/bluefin/pull/2130
> feat: embed actual image version into os-release

- Justfile
- build_files/base/00-image-info.sh
- build_files/base/01-build-fix.sh
- build_files/base/02-install-copr-repos.sh
- build_files/base/03-install-kernel-akmods.sh
- build_files/base/04-packages.sh
- build_files/base/05-override-install.sh
- build_files/base/07-base-image-changes.sh
- build_files/base/08-firmware.sh
- build_files/base/09-hwe-additions.sh
- build_files/base/10-brew.sh
- build_files/base/16-bootc.sh
- build_files/base/17-cleanup.sh
- build_files/base/18-workarounds.sh
- build_files/base/19-initramfs.sh
- build_files/dx/01-install-copr-repos-dx.sh
- build_files/dx/02-install-kernel-akmods-dx.sh
- build_files/dx/03-packages-dx.sh
- build_files/dx/04-override-install-dx.sh
- build_files/dx/09-cleanup-dx.sh
- build_files/shared/build-base.sh
- build_files/shared/build-dx.sh
- build_files/shared/clean-stage.sh
Port from https://github.com/ublue-os/bluefin/pull/2114
Tested on VM but if you could also test this
> feat(ci): Enable Docker Building, GHA Log Grouping

- Justfile
- just/aurora-apps.just
This is the result of running `just fix` with the same version of just used in the actions.
> chore: fix justfile

- Justfile
Same as https://github.com/ublue-os/bluefin/pull/2151
> fix(artifacthub): remove artifacthub category

- .github/workflows/build-image-stable.yml
- Justfile
Porting https://github.com/ublue-os/bluefin/pull/2168. Related to https://github.com/ublue-os/aurora/issues/158.
> feat: update stable kernel to 6.12.9

- just/aurora-apps.just
add udev rules for opentabletdriver
> feat: add udev rules on just recipe opentabletdriver

- aurora_flatpaks/flatpaks
- dx_flatpaks/flatpaks
- packages.json
add Font Downloader and Embelish for managing font just like [ bluefin](https://github.com/ublue-os/bluefin/pull/2175), also cleanup for package.json
> feat: add font downloader and embelish for managing fonts

- packages.json
> feat(dx): add ramalama

- system_files/shared/usr/libexec/ublue-flatpak-manager
Should fix https://github.com/ublue-os/aurora/issues/208 and https://github.com/ublue-os/aurora/issues/210
> fix: correctly pass argument to `ujust install-system-flatpaks`

- build_files/base/05-override-install.sh
Atuin might actually need this to be set
> fix: put bash-prexec back

- system_files/kinoite/usr/bin/dnf
- system_files/kinoite/usr/bin/yum
add warning when user trying to use dnf/yum just like [Bazzite](https://github.com/ublue-os/bazzite/commit/4b585c720eb7f22a883fa5a0bfe1ea05895b1c6c)
> feat: add warning when user use dnf/yum

- system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
https://github.com/ublue-os/bluefin/pull/2204
add beacondb for geolocation, this should fix automatic night light and timezones.
> feat: add beacondb geolocation for timezones

- build_files/base/02-install-copr-repos.sh
- build_files/base/05-override-install.sh
- packages.json
- system_files/kinoite/usr/bin/yum
small cleanup like using dnf config-manager addrepo for openrazer repository
> chore: small cleanup

- packages.json
This seems useful enough to include in the base image.
Closes #226.
> feat: add KSystemLog

- build_files/base/02-install-copr-repos.sh
- build_files/base/17-cleanup.sh
- build_files/dx/01-install-copr-repos-dx.sh
- build_files/dx/09-cleanup-dx.sh
From https://github.com/ublue-os/bluefin/pull/2218
> chore: use `ublue-os/packages` for ublue-related packages

- build_files/base/17-cleanup.sh
- build_files/dx/01-install-copr-repos-dx.sh
- build_files/dx/09-cleanup-dx.sh
Enable terra repos for dx build script too.
> feat: enable terra repo for dx building too

- build_files/shared/build-base.sh
Cherry picking https://github.com/ublue-os/bluefin/pull/2227.
> chore: remove rpm-ostree cli unwrapping

- build_files/base/17-cleanup.sh
- build_files/dx/01-install-copr-repos-dx.sh
- build_files/dx/04-override-install-dx.sh
Terra version of the devpod package causes issues and currently doesn't work.
This will switch back to the ublue-os COPR for DevPod
Fixes https://github.com/ublue-os/aurora/issues/263
> fix(devpod): switch back to the ublue copr for  devpod

- system_files/kinoite/usr/bin/dnf
- system_files/kinoite/usr/bin/yum
- system_files/shared/usr/lib/tmpfiles.d/yum.conf
Porting https://github.com/ublue-os/bazzite/pull/2357 and also replacing `yum` with a link to `dnf`.
> feat: add container detection to dnf

- build_files/dx/01-install-copr-repos-dx.sh
Move devpod packages back to terras fixed version
> chore: unswap devpod

- build_files/shared/build-base.sh
This reverts commit 2816a425e9f4ba9177cd9085cc53f38bc28f17d4.
> fix(revert): downgrade dnf5 to 5.2.10

- Justfile
> chore: update rechunker version

- Justfile
- build_files/base/18-workarounds.sh
from https://github.com/ublue-os/bluefin/pull/2285
> fix: Remove nonAscii file name for iso building

- build_files/base/07-base-image-changes.sh
stealing this from bazzite, this seems a little bit cleaner way to do it :p
https://github.com/ublue-os/bazzite/pull/2420
> fix: prepend the discover arguments

- build_files/base/04-packages.sh
- build_files/dx/03-packages-dx.sh
- packages.json
This cleans up the packages.json removing the kinoite objects. Also needed to do package exclusions as some packages are still missing from F42.
Also adds section for F42.
> chore: simplify packages.sh install scripts

- build_files/base/03-install-kernel-akmods.sh
Really a hack but should build fine now. Need to revert once rpmfusion is fixed
> fix: temp fix for rpmfusion on f42

- packages.json
Picked from bluefin, we should include this too. 
https://github.com/ublue-os/bluefin/pull/2321
> feat: Add samsung unified linux driver (#2321)

- build_files/dx/04-override-install-dx.sh
- packages.json
- system_files/dx/etc/yum.repos.d/docker-ce.repo
Install docker packages from testing repo until they are pushed to stable.
Also add the missing ls-iommu helper tool
> fix(dx): install docker-ce from test repo on F42

- packages.json
We haven't build F40 so this doesn't need to be here.
good bye, adios
> chore: remove f40 from package list

- build_files/base/03-install-kernel-akmods.sh
I don't believe this is needed anymore.
> chore: remove akmod workaround for beta

- just/aurora-apps.just
This recipe has diverged from Bluefin's at some point. I just copied and pasted it from the Bluefin repo and it seems to work now.
Closes #354.
> fix: setup-cockpit recipe

- build_files/base/03-install-kernel-akmods.sh
Remove xpadneo, analogue to https://github.com/ublue-os/bluefin/pull/2368.
> fix: remove xpadneo

- Justfile
- build_files/base/17-cleanup.sh
Seems that fedora is adding a service to enable fedora  flatpak repos
> fix(flatpak): remove fedora flatpak service and repos

- build_files/base/03-install-kernel-akmods.sh
> chore: use main repo for nvidia-install.sh

- just/aurora-system.just
> feat(just): add ujust for installing fonts from brew

- packages.json
Get rid of glorpfetch. it was a nice while it lasted.
> chore: get rid of glorpfetch

- build_files/base/05-override-install.sh
This  needs first the pr from https://github.com/ublue-os/aurora-docs/pull/69 to be merged and working first
> feat: add docs pdf

- .github/ISSUE_TEMPLATE/bug-report.yml
> chore: Update bug-report

- just/aurora-apps.just
> fix: fix small typo in just recipes

- just/aurora-system.just
ported from https://github.com/ublue-os/bluefin/pull/2449
> fix(just): add current user to dx-groups instead of root

- build_files/base/17-cleanup.sh
- packages.json
Enable uupd for all image builds
> feat: enable uupd for all images

- build_files/dx/01-install-copr-repos-dx.sh
- system_files/dx/usr/lib/systemd/system/aurora-dx-groups.service
- system_files/dx/usr/libexec/aurora-dx-groups
Removes some remnants of mentions of LXD
> chore: remove LXD from group scripts and references 

- .github/workflows/build-iso-latest.yml
- .github/workflows/build-isos.yml
- .github/workflows/reusable-build-iso.yml
Drops building of latest, HWE and DX ISOs
> chore: stop building -dx, HWE and latest ISOs

- README.md
Fix the star history chart in the readme.
> chore: update readme to fix star history chart

- .github/workflows/reusable-build-iso.yml
> fix(iso-build): change the build space part

- .github/workflows/generate-release.yml
for some reason our automatic changelogs are not done when stable builds, hopefully this fixes the issue
> fix(changelogs): fix changelogs automation

- build_files/base/17-cleanup.sh
> feat: enable input-remapper service by default

- .github/workflows/reusable-build-iso.yml
- Justfile
Needs changes to the ublue-os/aurora copr repo
> feat: add aurora branding to anaconda installer

- system_files/dx/usr/libexec/aurora-dx-groups
> fix: create devmode version directory

- system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
from https://github.com/ublue-os/bluefin/pull/2518
> fix: ublue-fix-hostname unit errors

- .github/workflows/reusable-build-iso.yml
> fix(iso): remove double build args

- packages.json
> feat: add polkit rules pkg

- .github/workflows/reusable-build-iso-anaconda.yml
> fix(iso): update workflow

- .github/workflows/reusable-build-iso-readymade.yml
> fix(readymade): fix workflow iso upload

- .github/workflows/reusable-build-iso-readymade.yml
- iso_files/configure_iso.sh
> fix(readymade): flatpaks for the iso

- iso_files/configure_iso.sh
> Revert "chore(readymade): taidan enablement"

- just/aurora-apps.just
> fix(just): use rpm -qa for list-installed-rpms

- build_files/base/07-base-image-changes.sh
- system_files/shared/usr/share/plasma/look-and-feel/dev.getaurora.aurora.desktop/contents/plasmoidsetupscripts/org.kde.plasma.folder.js
this affects only newly created users
wait with merge until new version of aurora-backgrounds is live on copr
> feat: change default wallpaper from chandeleer

- .github/workflows/reusable-build-iso-anaconda.yml
> chore(ci): Build live anaconda ISO weekly

- system_files/dx/usr/libexec/aurora-dx-user-vscode
This is replaced upstream, existing users get prompted to upgrade within vscode anyway
> fix: update docker extension to container extension

- just/aurora-apps.just
From https://github.com/ublue-os/bazzite/pull/2684
> feat: add exit and open web portal opts to sunshine setup script

- .github/CODEOWNERS
> chore: add renner to codeowners

- README.md
rendered README
https://github.com/ublue-os/aurora/blob/renner0e-patch-1/README.md
> feat: use new wallpaper for README

- .github/renovate.json5
- image-versions.yml
> fix: use the kinoite-main to kickoff build

- build_files/dx/09-cleanup-dx.sh
service was renamed in https://github.com/ublue-os/packages/pull/619
> fix: rename the libvirt workaround service

- build_files/base/07-base-image-changes.sh
- packages.json
> chore: remove discover KNewStuff backend properly

- just/aurora-system.just
Few things were dropped during refactoring
https://github.com/ublue-os/aurora/pull/305
https://github.com/ublue-os/aurora/pull/189
> fix(flatpaks): remove fedora repos and avoid collision with fedora flatpaks

- build_files/base/07-base-image-changes.sh
start-here logo is now our white-logo
needs https://github.com/ublue-os/packages/pull/651
> fix: use white logo for rebasers

- packages.json
nice little tool for wifi stuff
> feat: add iwd

- README.md
> feat: add active user count badge to README

- build_files/base/18-workarounds.sh
apparently this breaks kscreenlocker
https://bugzilla.redhat.com/show_bug.cgi?id=2375356
> fix(pin): qt6-qtwayland kscreenlocker regression

- build_files/base/07-base-image-changes.sh
wait with merge until 30.06.2025
> feat: update aurora wallpaper for july

- system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
stolen from bluefin
https://github.com/ublue-os/bluefin/pull/2729
> feat(motd): add KDE donation URL

- .github/workflows/build-image-beta.yml
We don't need the cronjobs on the workflow as renovate will update these from now on
> chore: cleanup beta workflow

- build_files/base/10-beta.sh
this only affects newly created users or people who have never changed anything on their panel
> feat(beta): replace discover with bazaar on panel and kickoff

- build_files/base/10-beta.sh
fix bazaar crashes under VMs and low spec PCs
> fix(beta): pin libdex to 0.9.1

- Justfile
> fix(build): update beta path to use correct tag

- build_files/base/10-beta.sh
following the lead on
https://github.com/ublue-os/bazzite/pull/2954
Beta only for now, Fedora should in my opinion push this change
> feat(beta): add sudo-rs

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
I forgot to commit a few changes in #734.
> fix(beta): update Bazaar banner alignment

- .github/ISSUE_TEMPLATE/feature_request.yml
same as https://github.com/ublue-os/bluefin/pull/2857
> chore: remove image dropdown from feat request template

- packages.json
pulled from https://github.com/ublue-os/bluefin/pull/2833
> feat: add davfs2 to support Taildrive

- build_files/base/10-beta.sh
Similar to https://github.com/ublue-os/packages/pull/768.
> feat(beta): set bazaar default for mimetype flatpakref

- .github/workflows/reusable-build.yml
followup to https://github.com/ublue-os/aurora/pull/757
this is included in the action itself now
> chore: remove unnecessary action

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Works pretty well and is Qt based.
> feat(bazaar): add Qt-based yt-dlp GUI

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
[Screencast_20250805_192414.webm](https://github.com/user-attachments/assets/f2eff2b4-5af4-459b-b539-1242b5d96891)
> fix(beta): move Bazaar text alignment to the correct side

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Also re-arranged a few apps in the Productivity section
> feat(bazaar): add Kdenlive + remove org.gnome.Fractal

- just/aurora-system.just
Fixes https://github.com/ublue-os/aurora/issues/809
> fix: typo in iwd toggle script

- .github/workflows/reusable-build-iso-anaconda.yml
picked from: https://github.com/ublue-os/bluefin/pull/2971
> feat: enable progress for ISO cloudflare upload

- system_files/shared/usr/share/ublue-os/user-setup.hooks.d/60-framework-kde-launcher.sh
maybe fixes:
https://github.com/ublue-os/aurora/issues/823
tested on my machine without the checks, just by executing this script
> fix(framework): use KDE javascript to set icon

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Requested in https://github.com/ublue-os/aurora/issues/854#issuecomment-3203742236.
> feat(bazaar): add OnlyOffice

- system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
- it's a cli
- we have it on the image
> fix(bazaar): add fwupd to blocklist

- system_files/shared/usr/share/ublue-os/motd/template.md
> fix: Revert "feat(motd): add mention of bbrew to motd"

- build_files/base/11-bazaar.sh
- just/aurora-apps.just
Adds the re-enablement to the ujust
fixes: https://github.com/ublue-os/aurora/issues/888
> fix: disable discover notifier

- build_files/base/00-image-info.sh
Following the other images, clean up the os-release
> fix(os-release): remove extra image info from os-release

- .github/workflows/build-image-stable.yml
Closes: https://github.com/ublue-os/aurora/issues/909
Also need the akmods PR https://github.com/ublue-os/akmods/pull/398 to be merged
> chore: unpin coreos-stable kernel

- .github/workflows/clean.yml
> chore: add missing images to cleanup workflow

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
> feat(bazaar): add ssh studio

- .github/workflows/reusable-build-iso-anaconda.yml
> chore: move ISO build to once a month

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Adds Yet Another Framework interface flatpak to Bazaars curated Utilities section
> feat: add yafi to bazaar

- build_files/base/07-base-image-changes.sh
needs: https://github.com/ublue-os/packages/pull/938
> feat: default to new wallpaper

- .github/workflows/build-image-beta.yml
- .github/workflows/build-image-latest-main.yml
- .github/workflows/build-image-stable.yml
we change this a lot so it makes sense to explicitly include it here
> feat(ci): ignore bazaar changes

- system_files/shared/usr/share/ublue-os/bazaar/config.yaml
filled a section up, discovered a cool image converter just now
> feat(bazaar): add more apps
